sudo: false

language: node_js

node_js:
    - 4
    - 6
    - 7
    - 8
    - 9

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm prune
    - npm install

script:
    - npm test
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const config = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: CrcPVUyye7mGAg1JkaGUNbkiRqX6Rjb2xMbmhBuKW9NW0gUTN5h7bhQhrD/N+er+GpPH+RXmfpbsX8FWgoUAqEDJpSX7SCPjGtSveExUiuOJSl5ZA1RMbaz7MhhJs5PPYlcp1HxGVt+NYZ8S8aAP5DS4EXWmbjnjyHZsgNKNcM7QgxU5vRjKcc/RuhfAVGg/CIdR/FSfMEZAjieF+WfkW8QRurvdA8+2KS+HriH6gmwc2di6GCGiqHVPcTUe2TFCVb0U4g6u+ykI7oq2NmgzBK1Im2aVjvxb02T6nF9mhFgAAcRVUXDxar0J/1GrgsUn4dvwsfxN2EAUqD4qN0XPqt+1QQZYFEYd7qcqobiKOJALUorHK3mi9CogSyYrxTllU7BSc62AK3mnUawzwWownUSSaFogkUaqnJl8Cftz19vm0GHjqPSaoc9QvuyxI4naUF0KdRDNXDtKV3CpBo5WupP29vOJx8DBN8yKKvVYxvx8oe4hsEJ+xe22IVkJUmSCTOWUJC2ASOZL7Q1RC8OckPzwNID3KRsyCVKqW0qZVrAGA3u8fopoCnFXqDAt4lxRiK0m6FJ/k26QasW5/+xv3jUvJ6aCJnyjcRKfahRkXRMRe934K4f+SoLMlDTzYKmMWRczgjiemoA4lygK73RaiMq7Hnpnb3C5PRbvcH9EaOs=
      on:
          node: 8
          repo: whizark/commitlint-config
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: TA1VvKyAbhysrBdjC8ndIfslaVQqKjgxrQfmdbpY0++fd5OsM5jN8erqA5BiUmfPWOmkmkH4vszM6wf4mamM0Wtpwvf5lkBlkKBKZNxoaoqsl8FuNqUXGXoaWdeuJwlEaUD5Q0RYrEy4muL/roQd5YVVVXaac0bg5JzjAdxPcm3xbSsyFC7R1AhbwVnJJOa5Slpza6Jn4IEEba7MEiV4mVKjqBhDsGn6PAJd0hNOv/LUyasgvbhWJbUgRftWxoA0OE+YTBlyUaIAPXcV2j36caW0U0jdAaMs1KyxSXOQp6FI0hoDPK1JE3cpfxpJvldPqR5sjs2QMeuVCGavwhuchBXCXtT5cx7gVnuwcgymrH8sPrFQjWekgryLLgPUo9saquP6kLzvqWhQLDUYjGiciJ4FZ8lR0EeB1iMXYyvt3xM+OI9ctPbBtK2S/JYvw1/y9FxaH1eBk1A/+vTjAKn41S5iMHf4RHUELJyFXAt7eWrGiXPHyoChsFOLPjEBHITHevofQDBrdpc0HL2LgqIZPZ3lbBwPku3mZxUYOBGSssRcmfb2wRRG7nws5sYm48JqrrDgFx15ixBargerMOCi7Nw1/N50p1AAme1agEaCdr4+yn7ZELUOUIA2vA3jwZfFEaPOu3LzJJkwBuAeAaKHz/0GP1xuzL2PBv6q9HKpLBo=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
